### ISSUE TITLE
Submission system timing out

### ISSUE THREAD

**Issue by AlexPlom** [NaskoVasilev/JudgeSystem#28]
Greetings, I am using the hosted version of this application (code-judgement.*.com), and have noticed that test submissions there are regularly timing out. Ones, that were passing flawlessly. Since i didn't believe it was an infrastructure downgrade, I decided to check the code.
 
After digging into some changes, I found the following pull request #25 . The change to the `DefaultAllowedTimeInMilliseconds` from 1500 to 10000 ms propagates down to the [Executor](https://github.com/NaskoVasilev/JudgeSystem/blob/f62405ba417a9d5ff77680e4bf44cca7ce02f542/Workers/JudgeSystem.Executors/Executor.cs#L78) where it is multiplied by 3. There we get a difference in the ms from `4500` to `30000`. The issues that I am facing, might be totally unrelated, but wanted to throw a heads up.

**Comment by Themikuma** [comment]
Actually this was done to combat the timing out. Timing out is currently caused by the server not being able to handle all of the requests.

**Comment by AlexPlom** [comment]
Thought that there might have been some relation to this, since the time where the issue started happening, overlaps with the pr. Will be closing this as unrelated and resolved.
